### ISSUE TITLE
Why *2 + 1

### ISSUE THREAD

**Issue by JunyuC032211** [rlindsberg/Thermometer-on-STM32F3-Discovery#8]
https://github.com/rlindsberg/Thermometer-on-STM32F3-Discovery/blob/16400d2d536fe846aee476508c9b8c822e72d68b/prerequisite%20project/Src/main.c#L84

**Comment by rlindsberg** [comment]
Därför att 2 poäng = 0b0011

**Comment by rlindsberg** [comment]
@JunyuC032211

**Comment by rlindsberg** [comment]
@JunyuC032211
